apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  namespace: cloudacademy
  labels:
    role: api
    env: demo
spec:
 rules:
 - host: api.X.X.X.X.nip.io
   http:
     paths:
     - path: /
       backend:
         serviceName: api
         servicePort: 8080